spring.application.name=apachesamza 


# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.retries=3

# Topic
app.kafka.topic=test-topic

# Batch configuration
app.kafka.batch.count=20
app.kafka.batch.message-prefix=Hello from Spring Boot
app.kafka.batch.key-prefix=startup-batch

# Logging
logging.level.com.example.kafkademo=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO