spring.application.name=kafka-demo
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.retries=3

# Topic
app.kafka.topic=binance-trades

# Stream Processing Configuration
app.stream.processing-interval=5000
app.stream.batch-size=5
app.stream.simulation-enabled=true

# Logging
logging.level.ru.lab.yana=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO